version: 2
jobs:
  build:
    
    working_directory: ~/ukrainiantolatin

    docker:
      - image: circleci/openjdk:8u171-jdk

    steps:

      - checkout

      - run: mvn dependency:go-offline
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
